### PR TITLE
[CLT-1757] Auto deploy docs microsite on changes to master

### PR DESCRIPTION
**Pull request by BlackstoneEngineering**
This will add a github action to track the master branch, and on changes to the src/main/**.java it will rebuild and push the microsite to treasure-data.github.io/td-android-sdk . 

Depends on : https://github.com/treasure-data/td-android-sdk/pull/68 - please merge this first.

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
@tung-vu-td 
1. The suggested install does not include javadoc, I tried it and it didn't work. I arrived at the current process after much debugging and trying the standard methods. 
2. The script does not modify the master branch. Rather it pulls the master branch, generates docs from it, and then pushes the docs to the gh-pages branch. Only gh-pages is modified. No changes at all are made to master.

**Comment by tung-vu-td** [comment]
Luckily I did managed to use the recommended script to run javadocSite task. Feel free to checkout and add review here: https://github.com/treasure-data/td-android-sdk/pull/68/files. Doing it this way will help us not to maintain setup java job in the long run.

**Comment by BlackstoneEngineering** [comment]
@tung-vu - so you were able to get it working and confirmed? If so then I will delete this PR.

**Comment by tung-vu-td** [comment]
@BlackstoneEngineering Yes, the action runs smoothly on my folk.

**Pull request closed without merging**
