### PR TITLE
Add comments doc for TreasureData

### PR DESCRIPTION
**Pull request by tung-vu-td**
Add missing comment doc for TreasureData

### CODE REVIEW

**Review by kietdo360 — APPROVED** [review]
LGTM

**Comment by BlackstoneEngineering** [comment]
@tung-vu - this is great! thank you! What is the tool / command to build these comments to markdown?

**Comment by tung-vu-td** [comment]
> @tung-vu - this is great! thank you! What is the tool / command to build these comments to markdown?

The tool to build these is `javadoc`

**Review by nmpennypacker — APPROVED** [review]
Reviewed for Data Exfiltrations

**Pull request merged**
